"""add origin-dest in ticket_model

Revision ID: 307699d7feb5
Revises: a897dd7a0874
Create Date: 2026-03-30 19:19:02.974518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307699d7feb5'
down_revision: Union[str, Sequence[str], None] = 'a897dd7a0874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('origin', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('dest', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'dest')
    op.drop_column('tickets', 'origin')
    # ### end Alembic commands ###
