"""add status

Revision ID: 9ecb058e120f
Revises: 307699d7feb5
Create Date: 2026-04-06 11:13:11.218112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecb058e120f'
down_revision: Union[str, Sequence[str], None] = '307699d7feb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_status', sa.Enum('paid', 'pending', 'failed', name='ticket_status'), server_default='paid', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('dest', sa.String(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('purchase_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('flight_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
