"""add new value to seat

Revision ID: a897dd7a0874
Revises: e2d7a7726de9
Create Date: 2026-03-29 01:35:47.200740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a897dd7a0874'
down_revision: Union[str, Sequence[str], None] = 'e2d7a7726de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE seat_status ADD VALUE IF NOT EXISTS 'Pending'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
