"""add status enum for ticket

Revision ID: ba605056221d
Revises: 307699d7feb5
Create Date: 2026-04-06 11:03:28.382125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba605056221d'
down_revision: Union[str, Sequence[str], None] = '307699d7feb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_status', sa.Enum('paid', 'pending', 'failed', name='ticket_status'), server_default='paid', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ticket_status')
    # ### end Alembic commands ###
