"""init

Revision ID: e2d7a7726de9
Revises: 209f91873e8d
Create Date: 2026-03-26 15:38:47.558496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d7a7726de9'
down_revision: Union[str, Sequence[str], None] = '209f91873e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplanes',
    sa.Column('airplane_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('seats_config', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('airplane_id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('reporting_airline', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('dest', sa.String(), nullable=False),
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.Column('is_delay', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.airplane_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('flight_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('origin_state', sa.String(), nullable=False),
    sa.Column('dest_state', sa.String(), nullable=False),
    sa.Column('crs_dep_time', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('diverted', sa.Boolean(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('distance_group', sa.Integer(), nullable=False),
    sa.Column('arr_delay', sa.Float(), nullable=False),
    sa.Column('arr_delay_minutes', sa.Float(), nullable=False),
    sa.Column('air_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('seat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(), nullable=False),
    sa.Column('seat_class', sa.Enum('Economy', 'Business', 'Comfort', 'First', name='seat_class'), server_default='Economy', nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('seat_status', sa.Enum('Free', 'Occupied', 'Booked', 'Blocked', name='seat_status'), server_default='Free', nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('purchase_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('flight_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('seats')
    op.drop_table('flight_details')
    op.drop_table('flights')
    op.drop_table('users')
    op.drop_table('airplanes')
    # ### end Alembic commands ###
