version: '3.8'

services:
  payment_db:
    image: postgres:15
    container_name: payment_db_cont
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - shared_flight_net # <--- ПРИВЯЗАЛИ К СЕТИ

  payment-app:
    build: .
    volumes:
      - .:/app
    container_name: payment_service_cont
    ports:
      - "8000:80"
    depends_on:
      - payment_db
    env_file:
      - .env
    networks:
      - shared_flight_net # <--- ПРИВЯЗАЛИ К СЕТИ

# <--- ОПИСАЛИ СЕТЬ В КОНЦЕ ФАЙЛА --->
networks:
  shared_flight_net:
    external: true
    name: flight_network