version: '3.8'

services:
  payment_db:
    image: postgres:15
    container_name: payment_db_cont
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - shared_flight_net

  payment-app:
    build: .
    volumes:
      - .:/app
    container_name: payment_service_cont
    ports:
      - "8000:80"
    depends_on:
      - payment_db
    env_file:
      - .env
    networks:
      - shared_flight_net

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_cli_cont
    command: >
      listen --forward-to payment-app:80/payment/webhook
      --api-key ${STRIPE_SECRET_KEY}
    env_file:
      - .env
    depends_on:
      - payment-app
    networks:
      - shared_flight_net

networks:
  shared_flight_net:
    external: true
    name: flight_network