"""empty message

Revision ID: 47f8280f538f
Revises: bd57dc06fd44
Create Date: 2026-02-03 17:52:45.086713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f8280f538f'
down_revision: Union[str, Sequence[str], None] = 'bd57dc06fd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('is_delay', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('reporting_airline', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('origin_state', sa.String(), nullable=False),
    sa.Column('dest', sa.String(), nullable=False),
    sa.Column('dest_state', sa.String(), nullable=False),
    sa.Column('crs_dep_time', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('diverted', sa.Boolean(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('distance_group', sa.Integer(), nullable=False),
    sa.Column('arr_delay', sa.Float(), nullable=False),
    sa.Column('arr_delay_minutes', sa.Float(), nullable=False),
    sa.Column('air_time', sa.Float(), nullable=False),
    sa.Column('ticket_class', sa.Enum('economy', 'comfort', 'business', 'first_class', name='ticketclass'), nullable=False),
    sa.Column('trip_type', sa.Enum('one_way', 'round_trip', name='triptype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('season', sa.Enum('summer', 'autumn', 'winter', 'spring', name='season'), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_dest_state'), 'tickets', ['dest_state'], unique=False)
    op.create_index(op.f('ix_tickets_origin_state'), 'tickets', ['origin_state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_tickets_origin_state'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_dest_state'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
