"""empty message

Revision ID: f1bf6524191b
Revises: 47f8280f538f
Create Date: 2026-02-03 17:53:56.989984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bf6524191b'
down_revision: Union[str, Sequence[str], None] = '47f8280f538f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute('UPDATE tickets SET user_id = 1')
    op.alter_column('tickets', 'user_id', nullable=False)
    op.create_index('ix_origin_dest_state', 'tickets', ['origin_state', 'dest_state'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index('ix_origin_dest_state', table_name='tickets')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###
