"""add stripe_id and url to db

Revision ID: a4bff6001af5
Revises: 4a7ae9dc698a
Create Date: 2026-04-07 18:16:48.482426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bff6001af5'
down_revision: Union[str, Sequence[str], None] = '4a7ae9dc698a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('stripe_url', sa.String(), nullable=True))
    op.add_column('payment', sa.Column('stripe_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'stripe_session_id')
    op.drop_column('payment', 'stripe_url')
    # ### end Alembic commands ###
