"""update Paymentmodel add ticket_id

Revision ID: 4a7ae9dc698a
Revises: b6f3d24c4d6c
Create Date: 2026-03-29 12:16:37.396222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7ae9dc698a'
down_revision: Union[str, Sequence[str], None] = 'b6f3d24c4d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('ticket_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'ticket_id')
    # ### end Alembic commands ###
