"""check

Revision ID: 01081b962a0a
Revises: 6ca3e57f2000
Create Date: 2026-03-12 00:38:33.156875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01081b962a0a'
down_revision: Union[str, Sequence[str], None] = '6ca3e57f2000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplanes',
    sa.Column('airplane_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('seats_config', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('airplane_id'),
    sa.UniqueConstraint('model_name')
    )
    op.drop_column('flight_details', 'total_seat')
    op.drop_column('flight_details', 'economy_class_seats')
    op.drop_column('flight_details', 'first_class_seat')
    op.drop_column('flight_details', 'business_class_seats')
    op.drop_column('flight_details', 'comfort_class_seats')
    op.add_column('flights', sa.Column('airplane_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'flights', 'airplanes', ['airplane_id'], ['airplane_id'])
    op.drop_column('flights', 'plane_model')
    op.add_column('tickets', sa.Column('passenger_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'passenger_name')
    op.add_column('flights', sa.Column('plane_model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'airplane_id')
    op.add_column('flight_details', sa.Column('comfort_class_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flight_details', sa.Column('business_class_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flight_details', sa.Column('first_class_seat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flight_details', sa.Column('economy_class_seats', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flight_details', sa.Column('total_seat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('airplanes')
    # ### end Alembic commands ###
